PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `Investment_Company` (
  `Investor` TEXT,
  `SOE` TEXT
);
INSERT INTO Investment_Company VALUES('Anhui Conch','No');
INSERT INTO Investment_Company VALUES('Beijing Jingneng & PowerChina','No');
INSERT INTO Investment_Company VALUES('China Datang','Yes');
INSERT INTO Investment_Company VALUES('China Everbright Group','No');
INSERT INTO Investment_Company VALUES('China General Nuclear Power Group','Yes');
INSERT INTO Investment_Company VALUES('China General Technology','Yes');
INSERT INTO Investment_Company VALUES('China Gezhouba','No');
INSERT INTO Investment_Company VALUES('China Hongqiao','No');
INSERT INTO Investment_Company VALUES('China Huadian Corporation','Yes');
INSERT INTO Investment_Company VALUES('China Huaneng Group','Yes');
INSERT INTO Investment_Company VALUES('China International Trust & Investment Corp - CITIC','No');
INSERT INTO Investment_Company VALUES('China Investment Corp','No');
INSERT INTO Investment_Company VALUES('China Machinery Engineering Corp','No');
INSERT INTO Investment_Company VALUES('China Metallurgical Group Corporation','Yes');
INSERT INTO Investment_Company VALUES('China National Building Material','Yes');
INSERT INTO Investment_Company VALUES('China National Chemical (ChemChina)','Yes');
INSERT INTO Investment_Company VALUES('China National Electrical Engineering Corporation','No');
INSERT INTO Investment_Company VALUES('China National Machinery Industry Corporation','Yes');
INSERT INTO Investment_Company VALUES('China National Offshore Oil Corporation','Yes');
INSERT INTO Investment_Company VALUES('China National Petroleum Corporation','Yes');
INSERT INTO Investment_Company VALUES('China North Industries','No');
INSERT INTO Investment_Company VALUES('China Oil and Foodstuffs Corporation (COFCO)','No');
INSERT INTO Investment_Company VALUES('China Southern Power Grid','Yes');
INSERT INTO Investment_Company VALUES('China Sunergy','No');
INSERT INTO Investment_Company VALUES('China Three Gorges Corporation','Yes');
INSERT INTO Investment_Company VALUES('Chinaerdos','No');
INSERT INTO Investment_Company VALUES('Chint','No');
INSERT INTO Investment_Company VALUES('Clenergy (Xiamen) Technology Co., Ltd','No');
INSERT INTO Investment_Company VALUES('Datang International Power Generation','No');
INSERT INTO Investment_Company VALUES('Envision Energy','No');
INSERT INTO Investment_Company VALUES('ET Solar','No');
INSERT INTO Investment_Company VALUES('ET SOLAR','No');
INSERT INTO Investment_Company VALUES('Fuxing Xiaocheng','No');
INSERT INTO Investment_Company VALUES('Guodian Group','No');
INSERT INTO Investment_Company VALUES('Hanergy Holding Group Ltd','No');
INSERT INTO Investment_Company VALUES('Harbin Electric','Yes');
INSERT INTO Investment_Company VALUES('Hareon Solar','No');
INSERT INTO Investment_Company VALUES('JA Solar','No');
INSERT INTO Investment_Company VALUES('Jiangsu Communication Clean Energy Technology (CCETC)','No');
INSERT INTO Investment_Company VALUES('Jiangsu Zhenfa Holdings','No');
INSERT INTO Investment_Company VALUES('Jinko Solar','No');
INSERT INTO Investment_Company VALUES('LDK Solar','No');
INSERT INTO Investment_Company VALUES(NULL,'No');
INSERT INTO Investment_Company VALUES('Nanjing Iron and Steel','Yes');
INSERT INTO Investment_Company VALUES('Panda Green Energy Group','No');
INSERT INTO Investment_Company VALUES('PowerChina','No');
INSERT INTO Investment_Company VALUES('ReneSola','No');
INSERT INTO Investment_Company VALUES('Risen Energy','No');
INSERT INTO Investment_Company VALUES('SDIC Power Holdings Co Ltd','No');
INSERT INTO Investment_Company VALUES('Shandong Ruyi','No');
INSERT INTO Investment_Company VALUES('Shanghai Electric','No');
INSERT INTO Investment_Company VALUES('Shenhua Group','No');
INSERT INTO Investment_Company VALUES('Shenzhen Energy','No');
INSERT INTO Investment_Company VALUES('Shenzhen Nanshan Power Co','No');
INSERT INTO Investment_Company VALUES('Shunfeng International Clean Energy Ltd','No');
INSERT INTO Investment_Company VALUES('Sinohydro','Yes');
INSERT INTO Investment_Company VALUES('Sinopec','Yes');
INSERT INTO Investment_Company VALUES('State Development and Investment','Yes');
INSERT INTO Investment_Company VALUES('State Grid Corporation of China','Yes');
INSERT INTO Investment_Company VALUES('State Power Investment Corporation','Yes');
INSERT INTO Investment_Company VALUES('Sungrow Power Supply','No');
INSERT INTO Investment_Company VALUES('Suntech','No');
INSERT INTO Investment_Company VALUES('Tebian Electric Apparatus (TBEA)','No');
INSERT INTO Investment_Company VALUES('Trina Solar','No');
INSERT INTO Investment_Company VALUES('Union Resources & Engineering Corporation','No');
INSERT INTO Investment_Company VALUES('Xiangtan Electric Manufacturing Co., Ltd','No');
INSERT INTO Investment_Company VALUES('Xinjiang Goldwind','No');
INSERT INTO Investment_Company VALUES('Yunnan Provincial Investment','No');
INSERT INTO Investment_Company VALUES('Yunnan Water Investment Co Ltd','No');
INSERT INTO Investment_Company VALUES('Zhefu Holdings','No');
INSERT INTO Investment_Company VALUES('Zhejiang Hengyi Group','No');
INSERT INTO Investment_Company VALUES('Zhejiang Kaishan Compressor','No');
INSERT INTO Investment_Company VALUES('Zhenfa New Energy','No');
INSERT INTO Investment_Company VALUES('ZTE','No');
INSERT INTO Investment_Company VALUES('3SBio, China International Trust and Investment (CITIC)','No');
INSERT INTO Investment_Company VALUES('Agile Property','No');
INSERT INTO Investment_Company VALUES('Aier Eye Hospital','No');
INSERT INTO Investment_Company VALUES('Alibaba','No');
INSERT INTO Investment_Company VALUES('Aluminum Corporation of China (Chinalco)','Yes');
INSERT INTO Investment_Company VALUES('Anbang','No');
INSERT INTO Investment_Company VALUES('Angel Yeast','No');
INSERT INTO Investment_Company VALUES('Anhui Foreign Economic Construction','No');
INSERT INTO Investment_Company VALUES('Anhui Landing','No');
INSERT INTO Investment_Company VALUES('Anhui Shanying','No');
INSERT INTO Investment_Company VALUES('Anhui Zhongding','No');
INSERT INTO Investment_Company VALUES('Ansteel','Yes');
INSERT INTO Investment_Company VALUES('Anta Sports-led consortium ','No');
INSERT INTO Investment_Company VALUES('Anton Oilfield Services','No');
INSERT INTO Investment_Company VALUES('Aoyuan','No');
INSERT INTO Investment_Company VALUES('Ashima Cultural Industry','No');
INSERT INTO Investment_Company VALUES('Asia Green Fund','No');
INSERT INTO Investment_Company VALUES('Asia Potash International','No');
INSERT INTO Investment_Company VALUES('Aviation Industry Corp. (AVIC)','Yes');
INSERT INTO Investment_Company VALUES('Aviation Industry Corp. (AVIC)-led consortium','Yes');
INSERT INTO Investment_Company VALUES('Aviation Industry Corp. (AVIC), Bank of China','Yes');
INSERT INTO Investment_Company VALUES('Aviation Industry Corp. (AVIC), China Railway Engineering','Yes');
INSERT INTO Investment_Company VALUES('Aviation Industry Corp. (AVIC), Han''s Laser','Yes');
INSERT INTO Investment_Company VALUES('Aviation Industry Corp. (AVIC), Jiangxi Water','Yes');
INSERT INTO Investment_Company VALUES('Aviation Industry Corp. (AVIC), Shanghai Construction','Yes');
INSERT INTO Investment_Company VALUES('Baidu','No');
INSERT INTO Investment_Company VALUES('Baidu, Ping An, Qihoo','No');
INSERT INTO Investment_Company VALUES('Baiyin Non-Ferrous, China International Trust and Investment (CITIC), Chang Xin','No');
INSERT INTO Investment_Company VALUES('Bank of China','No');
INSERT INTO Investment_Company VALUES('Bank of China, China Life, Hopu Investment','No');
INSERT INTO Investment_Company VALUES('BaoWu Steel (Baosteel)','Yes');
INSERT INTO Investment_Company VALUES('BBK Electronics','No');
INSERT INTO Investment_Company VALUES('BeiGene','No');
INSERT INTO Investment_Company VALUES('Beijing Auto (BAIC)','No');
INSERT INTO Investment_Company VALUES('Beijing Capital','No');
INSERT INTO Investment_Company VALUES('Beijing Construction Engineering','No');
INSERT INTO Investment_Company VALUES('Beijing Construction Engineering, Jiangxi International Cooperation Corp, Power Construction Corp. (PowerChina)','No');
INSERT INTO Investment_Company VALUES('Beijing Enterprises (BEHL)','No');
INSERT INTO Investment_Company VALUES('Beijing Jingmei','No');
INSERT INTO Investment_Company VALUES('Beijing Miteno','No');
INSERT INTO Investment_Company VALUES('Beijing Municipal Government','No');
INSERT INTO Investment_Company VALUES('Beijing Shanhai Capital, National IC Fund','No');
INSERT INTO Investment_Company VALUES('Beijing Shenwu','No');
INSERT INTO Investment_Company VALUES('Beijing Uni-Construction','No');
INSERT INTO Investment_Company VALUES('Beijing Urban Construction','No');
INSERT INTO Investment_Company VALUES('Beijing Zhonghuan','No');
INSERT INTO Investment_Company VALUES('Belle International, CDH','No');
INSERT INTO Investment_Company VALUES('BGI','No');
INSERT INTO Investment_Company VALUES('Biem.L.Fdlkk','No');
INSERT INTO Investment_Company VALUES('Biostime','No');
INSERT INTO Investment_Company VALUES('Bison Holding','No');
INSERT INTO Investment_Company VALUES('BlueFocus Communications','No');
INSERT INTO Investment_Company VALUES('Bomesc Offshore Engineering','No');
INSERT INTO Investment_Company VALUES('Bosai Minerals','No');
INSERT INTO Investment_Company VALUES('Boyu Capital, Hillhouse Capital','No');
INSERT INTO Investment_Company VALUES('Bright Foods','No');
INSERT INTO Investment_Company VALUES('Bright Foods, JIC, Shenzhen Donghuatong','No');
INSERT INTO Investment_Company VALUES('By-Health','No');
INSERT INTO Investment_Company VALUES('BYD','No');
INSERT INTO Investment_Company VALUES('Bytedance','No');
INSERT INTO Investment_Company VALUES('C Banner International','No');
INSERT INTO Investment_Company VALUES('Caixin, China International Trust and Investment (CITIC)','No');
INSERT INTO Investment_Company VALUES('CC Land','No');
INSERT INTO Investment_Company VALUES('CDH','No');
INSERT INTO Investment_Company VALUES('CDH, China Grand','No');
INSERT INTO Investment_Company VALUES('Cedar Group','No');
INSERT INTO Investment_Company VALUES('CEFC China Energy','No');
INSERT INTO Investment_Company VALUES('Central Walk','No');
INSERT INTO Investment_Company VALUES('Changsheng China','No');
INSERT INTO Investment_Company VALUES('Chengdu Techcent','No');
INSERT INTO Investment_Company VALUES('Chengdu Tianqi','No');
INSERT INTO Investment_Company VALUES('Chengdu Tianqi, China Investment Corporation (CIC)','No');
INSERT INTO Investment_Company VALUES('Chengtun Mining','No');
INSERT INTO Investment_Company VALUES('Chengtun Mining, Tsingshan','No');
INSERT INTO Investment_Company VALUES('Chery Auto','No');
INSERT INTO Investment_Company VALUES('Chifeng Jilong','No');
INSERT INTO Investment_Company VALUES('China Aerospace Science and Technology','Yes');
INSERT INTO Investment_Company VALUES('China Animal Husbandry','No');
INSERT INTO Investment_Company VALUES('China Architecture Design and Research','No');
INSERT INTO Investment_Company VALUES('China Chengtong','Yes');
INSERT INTO Investment_Company VALUES('China Communications Bank','No');
INSERT INTO Investment_Company VALUES('China Communications Construction','Yes');
INSERT INTO Investment_Company VALUES('China Communications Construction-led consortium','Yes');
INSERT INTO Investment_Company VALUES('China Communications Construction, China National Petroleum Corp. (CNPC)','Yes');
INSERT INTO Investment_Company VALUES('China Communications Construction, China Railway Construction','Yes');
INSERT INTO Investment_Company VALUES('China Communications Construction, China State Shipbuilding','Yes');
INSERT INTO Investment_Company VALUES('China Communications Construction, Guangxi Beibu','Yes');
INSERT INTO Investment_Company VALUES('China Communications Construction, Power Construction Corp. (PowerChina)','Yes');
INSERT INTO Investment_Company VALUES('China Communications Construction, State Construction Engineering','Yes');
INSERT INTO Investment_Company VALUES('China Communications Construction, Yanlord','Yes');
INSERT INTO Investment_Company VALUES('China Construction Bank','No');
INSERT INTO Investment_Company VALUES('China Copper Mines','No');
INSERT INTO Investment_Company VALUES('China Development Bank','No');
INSERT INTO Investment_Company VALUES('China Dreal','No');
INSERT INTO Investment_Company VALUES('China Eastern','Yes');
INSERT INTO Investment_Company VALUES('China Electric Equipment','Yes');
INSERT INTO Investment_Company VALUES('China Electronics Corporation','Yes');
INSERT INTO Investment_Company VALUES('China Electronics Technology','Yes');
INSERT INTO Investment_Company VALUES('China Energy Conservation and Environmental Protection','Yes');
INSERT INTO Investment_Company VALUES('China Energy Conservation and Environmental Protection, Jiangsu Dagang, China Tianying','Yes');
INSERT INTO Investment_Company VALUES('China Energy Engineering','No');
INSERT INTO Investment_Company VALUES('China Energy Engineering, China Minmetals','Yes');
INSERT INTO Investment_Company VALUES('China Energy Engineering, China National Machinery Industry (Sinomach)','Yes');
INSERT INTO Investment_Company VALUES('China Energy Engineering, Jiangsu Provincial Transport','No');
INSERT INTO Investment_Company VALUES('China Energy Engineering, Zhejiang Supcon','No');
INSERT INTO Investment_Company VALUES('China Energy Investment','No');
INSERT INTO Investment_Company VALUES('China Everbright','No');
INSERT INTO Investment_Company VALUES('China Everbright, Baofeng','No');
INSERT INTO Investment_Company VALUES('China Fortune','No');
INSERT INTO Investment_Company VALUES('China Galaxy Securities','No');
INSERT INTO Investment_Company VALUES('China GEM-led consortium','No');
INSERT INTO Investment_Company VALUES('China General Nuclear','Yes');
INSERT INTO Investment_Company VALUES('China General Nuclear, Southern Power Grid','Yes');
INSERT INTO Investment_Company VALUES('China General Technology (Genertec)','Yes');
INSERT INTO Investment_Company VALUES('China General Technology (Genertec), Beijing Power','Yes');
INSERT INTO Investment_Company VALUES('China General Technology (Genertec), Huawei Technologies','Yes');
INSERT INTO Investment_Company VALUES('China General Technology (Genertec), Power Construction Corp (PowerChina)','Yes');
INSERT INTO Investment_Company VALUES('China Grand','No');
INSERT INTO Investment_Company VALUES('China Huadian','Yes');
INSERT INTO Investment_Company VALUES('China International Trust and Investment (CITIC)','No');
INSERT INTO Investment_Company VALUES('China International Trust and Investment (CITIC)-led consortium','No');
INSERT INTO Investment_Company VALUES('China International Trust and Investment (CITIC)-led fund','No');
INSERT INTO Investment_Company VALUES('China International Trust and Investment (CITIC), Aluminum Corporation of China (Chinalco)','Yes');
INSERT INTO Investment_Company VALUES('China International Trust and Investment (CITIC), China Development Bank, Long March Capital','No');
INSERT INTO Investment_Company VALUES('China International Trust and Investment (CITIC), China Investment Corporation (CIC)','No');
INSERT INTO Investment_Company VALUES('China International Trust and Investment (CITIC), China National Petroleum Corp. (CNPC)','Yes');
INSERT INTO Investment_Company VALUES('China International Trust and Investment (CITIC), China Railway Construction','Yes');
INSERT INTO Investment_Company VALUES('China International Trust and Investment (CITIC), Sinohydro','No');
INSERT INTO Investment_Company VALUES('China Investment Corporation (CIC)','No');
INSERT INTO Investment_Company VALUES('China Investment Corporation (CIC), Beijing Jingdeshun','No');
INSERT INTO Investment_Company VALUES('China Investment Corporation (CIC), China Life','No');
INSERT INTO Investment_Company VALUES('China Investment Corporation (CIC), China Petroleum and Chemical (Sinopec)','Yes');
INSERT INTO Investment_Company VALUES('China Investment Corporation (CIC), Didi Kuaidi','No');
INSERT INTO Investment_Company VALUES('China Investment Corporation (CIC), Wise Road Capital','No');
INSERT INTO Investment_Company VALUES('China Iron and Steel Research Institute','Yes');
INSERT INTO Investment_Company VALUES('China Jinjiang Environment','No');
INSERT INTO Investment_Company VALUES('China Launch and Tracking Control General','No');
INSERT INTO Investment_Company VALUES('China Life','No');
INSERT INTO Investment_Company VALUES('China Life, Ping An','No');
INSERT INTO Investment_Company VALUES('China Light, Jiangxi Jianglian','No');
INSERT INTO Investment_Company VALUES('China Lilongwe Grand','No');
INSERT INTO Investment_Company VALUES('China Machine New Energy','No');
INSERT INTO Investment_Company VALUES('China Maple Leaf Educational','No');
INSERT INTO Investment_Company VALUES('China Media Capital, China International Trust and Investment (CITIC)','No');
INSERT INTO Investment_Company VALUES('China Merchants','Yes');
INSERT INTO Investment_Company VALUES('China Merchants, China Development Bank','Yes');
INSERT INTO Investment_Company VALUES('China Merchants, China Investment Corporation (CIC), China Ocean Shipping (COSCO)','Yes');
INSERT INTO Investment_Company VALUES('China Minsheng Investment','No');
INSERT INTO Investment_Company VALUES('China Mobile','Yes');
INSERT INTO Investment_Company VALUES('China Molybdenum','No');
INSERT INTO Investment_Company VALUES('China Molybdenum, Contemporary Amperex Tech','No');
INSERT INTO Investment_Company VALUES('China National Aviation Fuel','Yes');
INSERT INTO Investment_Company VALUES('China National Cereal, Oil and Foodstuffs (COFCO)','No');
INSERT INTO Investment_Company VALUES('China National Cereal, Oil and Foodstuffs (COFCO), Hopu Investment','No');
INSERT INTO Investment_Company VALUES('China National Chemical (ChemChina), State Administration of Foreign Exchange (SAFE)','No');
INSERT INTO Investment_Company VALUES('China National Chemical Engineering','Yes');
INSERT INTO Investment_Company VALUES('China National Chemical Engineering, China General Technology (Genertec)','Yes');
INSERT INTO Investment_Company VALUES('China National Chemical Engineering, Dongfang Electric, China Energy Engineering','Yes');
INSERT INTO Investment_Company VALUES('China National Chemical Engineering, East China Engineering','Yes');
INSERT INTO Investment_Company VALUES('China National Machinery Industry (Sinomach)','Yes');
INSERT INTO Investment_Company VALUES('China National Machinery Industry (Sinomach)-led consortium','Yes');
INSERT INTO Investment_Company VALUES('China National Machinery Industry (Sinomach), China National Chemical Engineering','Yes');
INSERT INTO Investment_Company VALUES('China National Machinery Industry (Sinomach), China Nonferrous','Yes');
INSERT INTO Investment_Company VALUES('China National Machinery Industry (Sinomach), Gezhouba','Yes');
INSERT INTO Investment_Company VALUES('China National Machinery Industry (Sinomach), Shanghai Electric','Yes');
INSERT INTO Investment_Company VALUES('China National Machinery Industry (Sinomach), Sinohydro','Yes');
INSERT INTO Investment_Company VALUES('China National Machinery Industry (Sinomach), Sinopharm','Yes');
INSERT INTO Investment_Company VALUES('China National Nuclear','Yes');
INSERT INTO Investment_Company VALUES('China National Off-shore Oil (CNOOC)','Yes');
INSERT INTO Investment_Company VALUES('China National Off-shore Oil (CNOOC), China Petroleum and Chemical (Sinopec)','Yes');
INSERT INTO Investment_Company VALUES('China National Petroleum Corp. (CNPC)','Yes');
INSERT INTO Investment_Company VALUES('China National Petroleum Corp. (CNPC), China National Off-shore Oil (CNOOC)','Yes');
INSERT INTO Investment_Company VALUES('China National Petroleum Corp. (CNPC), China Petroleum and Chemical (Sinopec)','Yes');
INSERT INTO Investment_Company VALUES('China National Petroleum Corp. (CNPC), China State Shipbuilding','Yes');
INSERT INTO Investment_Company VALUES('China National Silicon','No');
INSERT INTO Investment_Company VALUES('China National Silicon (consortium of Shanghai state firms)','No');
INSERT INTO Investment_Company VALUES('China New Hope','No');
INSERT INTO Investment_Company VALUES('China Nickel Resources','No');
INSERT INTO Investment_Company VALUES('China Nonferrous','Yes');
INSERT INTO Investment_Company VALUES('China Nonferrous, China Railway Construction','Yes');
INSERT INTO Investment_Company VALUES('China North Industries (Norinco)','No');
INSERT INTO Investment_Company VALUES('China North Industries (Norinco)-led consortium','No');
INSERT INTO Investment_Company VALUES('China North Industries (Norinco), Shandong Taikai Group','No');
INSERT INTO Investment_Company VALUES('China Ocean Shipping (COSCO)','Yes');
INSERT INTO Investment_Company VALUES('China Ocean Shipping (COSCO), State Administration of Foreign Exchange (SAFE)','Yes');
INSERT INTO Investment_Company VALUES('China Oil HBP','No');
INSERT INTO Investment_Company VALUES('China Orient Asset Management','No');
INSERT INTO Investment_Company VALUES('China Petroleum and Chemical (Sinopec)','Yes');
INSERT INTO Investment_Company VALUES('China Petroleum and Chemical (Sinopec), China General Technology (Genertec)','Yes');
INSERT INTO Investment_Company VALUES('China Petroleum and Chemical (Sinopec), China Huadian Corporation (Huadian)','Yes');
INSERT INTO Investment_Company VALUES('China Petroleum and Chemical (Sinopec), Jiangxi Water','Yes');
INSERT INTO Investment_Company VALUES('China Poly','No');
INSERT INTO Investment_Company VALUES('China Poly, State Construction Engineering','No');
INSERT INTO Investment_Company VALUES('China Power Engineering Consulting','Yes');
INSERT INTO Investment_Company VALUES('China Power Investment','No');
INSERT INTO Investment_Company VALUES('China Railway Construction','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction-led consortium','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction, Aviation Industry Corp. (AVIC)','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction, Changjiang Yichang Waterway','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction, China Energy Engineering','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction, China General Technology (Genertec)','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction, China Nonferrous','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction, China Railway Engineering','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction, China Railway Engineering, China Communications Construction','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction, Nanjing Government, China Development Bank, Guangdong Xinguang','Yes');
INSERT INTO Investment_Company VALUES('China Railway Construction, Tongling Nonferrous','Yes');
INSERT INTO Investment_Company VALUES('China Railway Corp, China North Industries (Norinco)','Yes');
INSERT INTO Investment_Company VALUES('China Railway Corp., China Railway Engineering','Yes');
INSERT INTO Investment_Company VALUES('China Railway Engineering','Yes');
INSERT INTO Investment_Company VALUES('China Railway Engineering-led consortium','Yes');
INSERT INTO Investment_Company VALUES('China Railway Engineering, Beijing Construction Engineering','Yes');
INSERT INTO Investment_Company VALUES('China Railway Engineering, China General Technology (Genertec)','Yes');
INSERT INTO Investment_Company VALUES('China Railway Engineering, Power Construction Corp. (PowerChina)','Yes');
INSERT INTO Investment_Company VALUES('China Railway Rolling Stock Corp. (CRR) ','No');
INSERT INTO Investment_Company VALUES('China Railway Signal and Communication','No');
INSERT INTO Investment_Company VALUES('China Reform Holdings','No');
INSERT INTO Investment_Company VALUES('China Reform Holdings, China National Chemical (ChemChina)','No');
INSERT INTO Investment_Company VALUES('China Reinsurance','No');
INSERT INTO Investment_Company VALUES('China Resources','Yes');
INSERT INTO Investment_Company VALUES('China Risun-led consortium','No');
INSERT INTO Investment_Company VALUES('China Shipping','No');
INSERT INTO Investment_Company VALUES('China Shipping, China Ocean Shipping (COSCO), China Merchants','Yes');
INSERT INTO Investment_Company VALUES('China Small and Medium Enterprise Investment','No');
INSERT INTO Investment_Company VALUES('China South Industries','No');
INSERT INTO Investment_Company VALUES('China South Locomotive','No');
INSERT INTO Investment_Company VALUES('China State Shipbuilding','Yes');
INSERT INTO Investment_Company VALUES('China Telecom','Yes');
INSERT INTO Investment_Company VALUES('China Tianying','No');
INSERT INTO Investment_Company VALUES('China United Network Communications (Unicom)','No');
INSERT INTO Investment_Company VALUES('China Vanke','No');
INSERT INTO Investment_Company VALUES('China Vanke, Hopu Investment, Hillhouse Capital, Bank of China','No');
INSERT INTO Investment_Company VALUES('China Western Power Industrial','No');
INSERT INTO Investment_Company VALUES('China Youth Travel Services','No');
INSERT INTO Investment_Company VALUES('ChinaNetCenter','No');
INSERT INTO Investment_Company VALUES('Chinese Academy of Sciences','No');
INSERT INTO Investment_Company VALUES('Chongqing Chonggang','No');
INSERT INTO Investment_Company VALUES('Chongqing Foreign Trade and Economic Cooperation','No');
INSERT INTO Investment_Company VALUES('Chongqing Grain','No');
INSERT INTO Investment_Company VALUES('Chongqing Sokon','No');
INSERT INTO Investment_Company VALUES('Chongqing USUM','No');
INSERT INTO Investment_Company VALUES('Cinda','No');
INSERT INTO Investment_Company VALUES('Cinda, Union Life','No');
INSERT INTO Investment_Company VALUES('CNIC','No');
INSERT INTO Investment_Company VALUES('Comtec Solar','No');
INSERT INTO Investment_Company VALUES('Contemporary Amperex Tech','No');
INSERT INTO Investment_Company VALUES('Contemporary Amperex Tech, Guangdong Brunp Recycling','No');
INSERT INTO Investment_Company VALUES('Country Garden','No');
INSERT INTO Investment_Company VALUES('Creat','No');
INSERT INTO Investment_Company VALUES('Cultural Investment','No');
INSERT INTO Investment_Company VALUES('Cybernaut','No');
INSERT INTO Investment_Company VALUES('Dahua Group','No');
INSERT INTO Investment_Company VALUES('Dalian International Cooperation Corp','No');
INSERT INTO Investment_Company VALUES('Dalian Jiayou','No');
INSERT INTO Investment_Company VALUES('Dalian Jiayou, Zijing Mining','No');
INSERT INTO Investment_Company VALUES('Dalian Shipbuilding','No');
INSERT INTO Investment_Company VALUES('Dalian Wanda','No');
INSERT INTO Investment_Company VALUES('Dalian Wanda, Ridong','No');
INSERT INTO Investment_Company VALUES('Dare Group','No');
INSERT INTO Investment_Company VALUES('Datang','Yes');
INSERT INTO Investment_Company VALUES('Datang Power, China South Industries','Yes');
INSERT INTO Investment_Company VALUES('Datong','No');
INSERT INTO Investment_Company VALUES('DCP Captial','No');
INSERT INTO Investment_Company VALUES('Didi Chuxing','No');
INSERT INTO Investment_Company VALUES('Didi Kuaidi','No');
INSERT INTO Investment_Company VALUES('Dongbei Steel','No');
INSERT INTO Investment_Company VALUES('Dongfang Electric','No');
INSERT INTO Investment_Company VALUES('Dongfang Electric, Shanghai Electric','No');
INSERT INTO Investment_Company VALUES('Dongfeng Motor','Yes');
INSERT INTO Investment_Company VALUES('East China Mineral Exploration and Development Bureau (Jiangsu)','No');
INSERT INTO Investment_Company VALUES('ENN Energy','No');
INSERT INTO Investment_Company VALUES('Envision Group','No');
INSERT INTO Investment_Company VALUES('Everbright','No');
INSERT INTO Investment_Company VALUES('Everest Medicines','No');
INSERT INTO Investment_Company VALUES('Evergrande Group','No');
INSERT INTO Investment_Company VALUES('Evergreen','No');
INSERT INTO Investment_Company VALUES('Ex-Im Bank','No');
INSERT INTO Investment_Company VALUES('Feihe International','No');
INSERT INTO Investment_Company VALUES('Feishang Group','No');
INSERT INTO Investment_Company VALUES('Film Carnival','No');
INSERT INTO Investment_Company VALUES('First Auto Works, China Development Bank','No');
INSERT INTO Investment_Company VALUES('Fortune Fountain Capital','No');
INSERT INTO Investment_Company VALUES('Fosun','No');
INSERT INTO Investment_Company VALUES('Fujian Construction Engineering','No');
INSERT INTO Investment_Company VALUES('Fujian Construction Engineering, China Communications Construction, Minmetals','Yes');
INSERT INTO Investment_Company VALUES('Fujian Thai Hot','No');
INSERT INTO Investment_Company VALUES('Fulida Group','No');
INSERT INTO Investment_Company VALUES('Fullshare','No');
INSERT INTO Investment_Company VALUES('Fuyao Glass','No');
INSERT INTO Investment_Company VALUES('Gansu Gangtai','No');
INSERT INTO Investment_Company VALUES('Gansu International Cooperation Corp','No');
INSERT INTO Investment_Company VALUES('Gansu Tianqing','No');
INSERT INTO Investment_Company VALUES('GDS','No');
INSERT INTO Investment_Company VALUES('GEM','No');
INSERT INTO Investment_Company VALUES('GEM, Zhejiang Weiming','No');
INSERT INTO Investment_Company VALUES('Genimous Investment','No');
INSERT INTO Investment_Company VALUES('Genzon','No');
INSERT INTO Investment_Company VALUES('Geo-Jade Petroleum','Yes');
INSERT INTO Investment_Company VALUES('Gezhouba','No');
INSERT INTO Investment_Company VALUES('Gezhouba, Xinjiang International Cooperation Corp','No');
INSERT INTO Investment_Company VALUES('Global Logistics Properties','No');
INSERT INTO Investment_Company VALUES('GoerTek','No');
INSERT INTO Investment_Company VALUES('Gold One','No');
INSERT INTO Investment_Company VALUES('Golden Dragon','No');
INSERT INTO Investment_Company VALUES('Goldleaf Jewelry','No');
INSERT INTO Investment_Company VALUES('Goodbaby','No');
INSERT INTO Investment_Company VALUES('Goodix Technology','No');
INSERT INTO Investment_Company VALUES('GR Investment, China International Trust and Investment (CITIC)','No');
INSERT INTO Investment_Company VALUES('Great Wall','No');
INSERT INTO Investment_Company VALUES('GSR','No');
INSERT INTO Investment_Company VALUES('Guangdong Changda Highway Engineering','No');
INSERT INTO Investment_Company VALUES('Guangdong Heng Fu','No');
INSERT INTO Investment_Company VALUES('Guangdong New South','No');
INSERT INTO Investment_Company VALUES('Guangdong Nuclear Power, China Development Bank','Yes');
INSERT INTO Investment_Company VALUES('Guangdong Overseas Construction','No');
INSERT INTO Investment_Company VALUES('Guangdong Power Engineering','No');
INSERT INTO Investment_Company VALUES('Guangdong Province, Huaneng Power','Yes');
INSERT INTO Investment_Company VALUES('Guangdong Rising Asset Management','No');
INSERT INTO Investment_Company VALUES('Guangdong Wencan','No');
INSERT INTO Investment_Company VALUES('Guangxi Beibu','No');
INSERT INTO Investment_Company VALUES('Guangxi Investment','No');
INSERT INTO Investment_Company VALUES('Guangxi Liugong Machinery','No');
INSERT INTO Investment_Company VALUES('Guangxi Nonferrous','No');
INSERT INTO Investment_Company VALUES('Guangxi Road and Bridge','No');
INSERT INTO Investment_Company VALUES('Guangzhou Dongsong','No');
INSERT INTO Investment_Company VALUES('Guangzhou R&F Properties','No');
INSERT INTO Investment_Company VALUES('Guangzhou R&F Properties, CC Land','No');
INSERT INTO Investment_Company VALUES('Guizhou Highway Engineering','No');
INSERT INTO Investment_Company VALUES('Guizhou Hongfu','No');
INSERT INTO Investment_Company VALUES('Guizhou Transportation Planning','No');
INSERT INTO Investment_Company VALUES('Guizhou Tyre','No');
INSERT INTO Investment_Company VALUES('Guodian','No');
INSERT INTO Investment_Company VALUES('Guotsing','No');
INSERT INTO Investment_Company VALUES('Guoxuan','No');
INSERT INTO Investment_Company VALUES('Haicheng Xiyang Group','No');
INSERT INTO Investment_Company VALUES('Haier','No');
INSERT INTO Investment_Company VALUES('Hailiang','No');
INSERT INTO Investment_Company VALUES('Haitong Securities','No');
INSERT INTO Investment_Company VALUES('Hanergy','No');
INSERT INTO Investment_Company VALUES('Hangzhou Great Star','No');
INSERT INTO Investment_Company VALUES('Hangzhou Lianluo Interactive','No');
INSERT INTO Investment_Company VALUES('Hanrui Cobalt, Qingyuan Keweike Mineral ','No');
INSERT INTO Investment_Company VALUES('Harbin Electric, China Energy Engineering','Yes');
INSERT INTO Investment_Company VALUES('Harbin Electric, State Administration of Foreign Exchange (SAFE)','Yes');
INSERT INTO Investment_Company VALUES('Health and Happiness','No');
INSERT INTO Investment_Company VALUES('Hebei Construction and Investment','No');
INSERT INTO Investment_Company VALUES('Hebei Rujiang','No');
INSERT INTO Investment_Company VALUES('Hebei Steel','No');
INSERT INTO Investment_Company VALUES('Hebei Steel, General Development, Tewoo','No');
INSERT INTO Investment_Company VALUES('Hebei Zhongbo Platinum','No');
INSERT INTO Investment_Company VALUES('Hefei Ray Capital Management','No');
INSERT INTO Investment_Company VALUES('Heilongjiang Construction','No');
INSERT INTO Investment_Company VALUES('Heilongjiang Grand Farm','No');
INSERT INTO Investment_Company VALUES('Henan Civil Aviation','No');
INSERT INTO Investment_Company VALUES('Henan Guoju','No');
INSERT INTO Investment_Company VALUES('Henan International Cooperation Corp','No');
INSERT INTO Investment_Company VALUES('Henan International Cooperation Corp, China City Construction','No');
INSERT INTO Investment_Company VALUES('Henan International Cooperation Corp, China Railway Engineering, China Energy Conservation and Environmental Protection, Fujian Construction Engineering','Yes');
INSERT INTO Investment_Company VALUES('Henan Meijing','No');
INSERT INTO Investment_Company VALUES('Henan Senyuan','No');
INSERT INTO Investment_Company VALUES('Hengkang Medical','No');
INSERT INTO Investment_Company VALUES('Hengtong Group','No');
INSERT INTO Investment_Company VALUES('Highland Fund','No');
INSERT INTO Investment_Company VALUES('Highsun','No');
INSERT INTO Investment_Company VALUES('Hillhouse Capital','No');
INSERT INTO Investment_Company VALUES('Hillhouse Capital-led consortium','No');
INSERT INTO Investment_Company VALUES('Hisense Group','No');
INSERT INTO Investment_Company VALUES('HNA','No');
INSERT INTO Investment_Company VALUES('HNA, Jin Jiang International','No');
INSERT INTO Investment_Company VALUES('Hodo Group','No');
INSERT INTO Investment_Company VALUES('Holley Group, Futong Group','No');
INSERT INTO Investment_Company VALUES('Honbridge','No');
INSERT INTO Investment_Company VALUES('Honbridge Capital','No');
INSERT INTO Investment_Company VALUES('Hongbo Group','No');
INSERT INTO Investment_Company VALUES('Hongdou','No');
INSERT INTO Investment_Company VALUES('Hongqiao','No');
INSERT INTO Investment_Company VALUES('Hongshi','No');
INSERT INTO Investment_Company VALUES('Hongye Investment','No');
INSERT INTO Investment_Company VALUES('Hopu Investment','No');
INSERT INTO Investment_Company VALUES('Hosen Capital, China New Hope','No');
INSERT INTO Investment_Company VALUES('Huajian','No');
INSERT INTO Investment_Company VALUES('Huaneng Power','Yes');
INSERT INTO Investment_Company VALUES('Huapont','No');
INSERT INTO Investment_Company VALUES('Huarong','No');
INSERT INTO Investment_Company VALUES('Huatai Securities','No');
INSERT INTO Investment_Company VALUES('Huawei Technologies','No');
INSERT INTO Investment_Company VALUES('Huaxin Cement','No');
INSERT INTO Investment_Company VALUES('Huaxin Post and Telecom','No');
INSERT INTO Investment_Company VALUES('Huayi Brothers','No');
INSERT INTO Investment_Company VALUES('Huazhu Hotels','No');
INSERT INTO Investment_Company VALUES('Hubei Fuxing Science','No');
INSERT INTO Investment_Company VALUES('Hubei Province Investment Arm','No');
INSERT INTO Investment_Company VALUES('Humanwell Healthcare','No');
INSERT INTO Investment_Company VALUES('Humanwell Healthcare, China International Trust and Investment (CITIC)','No');
INSERT INTO Investment_Company VALUES('Hunan Construction Engineering','No');
INSERT INTO Investment_Company VALUES('Hunan Construction Engineering, China Energy Conservation and Environmental Protection','Yes');
INSERT INTO Investment_Company VALUES('Hunan TV','No');
INSERT INTO Investment_Company VALUES('Hunan Valin','No');
INSERT INTO Investment_Company VALUES('Hunan Zhongwei','No');
INSERT INTO Investment_Company VALUES('Hydrochina','No');
INSERT INTO Investment_Company VALUES('iCarbonX','No');
INSERT INTO Investment_Company VALUES('IDG Capital','No');
INSERT INTO Investment_Company VALUES('IDG Capital, MLS, Yiwu State-Owned Assets','No');
INSERT INTO Investment_Company VALUES('Industrial and Commercial Bank of China','No');
INSERT INTO Investment_Company VALUES('Inner Mongolia Hongjun','No');
INSERT INTO Investment_Company VALUES('Inner Mongolia Yili Industrial','No');
INSERT INTO Investment_Company VALUES('Inspur Group','No');
INSERT INTO Investment_Company VALUES('JAC Motors','No');
INSERT INTO Investment_Company VALUES('Jangho','No');
INSERT INTO Investment_Company VALUES('Jason Furniture','No');
INSERT INTO Investment_Company VALUES('JCHX Mining','No');
INSERT INTO Investment_Company VALUES('JCHX Mining, China Railway Construction','Yes');
INSERT INTO Investment_Company VALUES('JD.com','No');
INSERT INTO Investment_Company VALUES('Jereh Group','No');
INSERT INTO Investment_Company VALUES('JiaHe JianAn','No');
INSERT INTO Investment_Company VALUES('Jiangnan Mould and Plastic','No');
INSERT INTO Investment_Company VALUES('Jiangsu Changjiang, Semiconductor Manufacturing International, National IC Fund','No');
INSERT INTO Investment_Company VALUES('Jiangsu Delong','No');
INSERT INTO Investment_Company VALUES('Jiangsu Hengyuan','No');
INSERT INTO Investment_Company VALUES('Jiangsu International Cooperation Corp','No');
INSERT INTO Investment_Company VALUES('Jiangsu Jinsheng','No');
INSERT INTO Investment_Company VALUES('Jiangsu Lianfa','No');
INSERT INTO Investment_Company VALUES('Jiangsu Lianhe','No');
INSERT INTO Investment_Company VALUES('Jiangsu Longze','No');
INSERT INTO Investment_Company VALUES('Jiangsu Lopal','No');
INSERT INTO Investment_Company VALUES('Jiangsu Nantong','No');
INSERT INTO Investment_Company VALUES('Jiangsu Overseas Cooperation and Investment-led consortium','No');
INSERT INTO Investment_Company VALUES('Jiangsu Qiyuan','No');
INSERT INTO Investment_Company VALUES('Jiangsu Shagang','No');
INSERT INTO Investment_Company VALUES('Jiangsu Shagang-led consortium','No');
INSERT INTO Investment_Company VALUES('Jiangsu Shagang, RGL Group','No');
INSERT INTO Investment_Company VALUES('Jiangsu Sunshine','No');
INSERT INTO Investment_Company VALUES('Jiangsu Taihu','No');
INSERT INTO Investment_Company VALUES('Jiangsu Yabang','No');
INSERT INTO Investment_Company VALUES('Jiangsu Yongding, China National Machinery Industry (Sinomach)','No');
INSERT INTO Investment_Company VALUES('Jiangsu Yongding, Harbin Electric','Yes');
INSERT INTO Investment_Company VALUES('Jiangsu Yuejin','No');
INSERT INTO Investment_Company VALUES('Jiangsu Zongyi','No');
INSERT INTO Investment_Company VALUES('Jiangxi Copper','No');
INSERT INTO Investment_Company VALUES('Jiangxi Ganfeng','No');
INSERT INTO Investment_Company VALUES('Jiangxi Holitech','No');
INSERT INTO Investment_Company VALUES('Jiangxi International Cooperation Corp','No');
INSERT INTO Investment_Company VALUES('Jiangxi International Cooperation Corp, Henan International Cooperation Corp','No');
INSERT INTO Investment_Company VALUES('Jiangxi investors','No');
INSERT INTO Investment_Company VALUES('Jiangxi Transportation Engineering, Fujian Construction Engineering','No');
INSERT INTO Investment_Company VALUES('Jiangxi Wanguo, AXF','No');
INSERT INTO Investment_Company VALUES('Jiangxi Zhongmei','No');
INSERT INTO Investment_Company VALUES('Jianlong Investment ','No');
INSERT INTO Investment_Company VALUES('Jilin Nonferrous','No');
INSERT INTO Investment_Company VALUES('Jin Jiang International','No');
INSERT INTO Investment_Company VALUES('Jinchuan Group','No');
INSERT INTO Investment_Company VALUES('Jinchuan Group, China Development Bank','No');
INSERT INTO Investment_Company VALUES('Jingxing Paper','No');
INSERT INTO Investment_Company VALUES('Jinsheng Trading','No');
INSERT INTO Investment_Company VALUES('Jiquan Iron and Steel','No');
INSERT INTO Investment_Company VALUES('JL Mag Rare-Earth','No');
INSERT INTO Investment_Company VALUES('Jumei','No');
INSERT INTO Investment_Company VALUES('Keep Glory','No');
INSERT INTO Investment_Company VALUES('Keer Group','No');
INSERT INTO Investment_Company VALUES('Kingho Energy','No');
INSERT INTO Investment_Company VALUES('Konfoong Materials','No');
INSERT INTO Investment_Company VALUES('Kunming Iron','No');
INSERT INTO Investment_Company VALUES('Lander Sports','No');
INSERT INTO Investment_Company VALUES('Landsea','No');
INSERT INTO Investment_Company VALUES('LeEco','No');
INSERT INTO Investment_Company VALUES('Legend','No');
INSERT INTO Investment_Company VALUES('Lenovo','No');
INSERT INTO Investment_Company VALUES('Leyard Optoelectronics','No');
INSERT INTO Investment_Company VALUES('Liaoning Port','No');
INSERT INTO Investment_Company VALUES('Lifan','No');
INSERT INTO Investment_Company VALUES('Lingsheng Investment','No');
INSERT INTO Investment_Company VALUES('LinkGlobal Logistics','No');
INSERT INTO Investment_Company VALUES('Liuhe','No');
INSERT INTO Investment_Company VALUES('Loctek Ergonomic','No');
INSERT INTO Investment_Company VALUES('Logan Property, Nanshan Group','No');
INSERT INTO Investment_Company VALUES('LONGi Green Energy','No');
INSERT INTO Investment_Company VALUES('Luxshare','No');
INSERT INTO Investment_Company VALUES('Luye Life Sciences','No');
INSERT INTO Investment_Company VALUES('MCC','No');
INSERT INTO Investment_Company VALUES('MCC, China Architecture Design','No');
INSERT INTO Investment_Company VALUES('MCC, Jiangxi Copper','No');
INSERT INTO Investment_Company VALUES('MCC, Sinohydro','No');
INSERT INTO Investment_Company VALUES('Meidu Holding','No');
INSERT INTO Investment_Company VALUES('Meituan Dianping-led consortium','No');
INSERT INTO Investment_Company VALUES('Midea','No');
INSERT INTO Investment_Company VALUES('MIE, Can-China Global Resources','No');
INSERT INTO Investment_Company VALUES('Mindray Medical','No');
INSERT INTO Investment_Company VALUES('Ming Yan','No');
INSERT INTO Investment_Company VALUES('Ming Yuan Silu','No');
INSERT INTO Investment_Company VALUES('Minmetals','Yes');
INSERT INTO Investment_Company VALUES('Minmetals, Fujian Construction Engineering','Yes');
INSERT INTO Investment_Company VALUES('Minmetals, Jiangxi Copper','Yes');
INSERT INTO Investment_Company VALUES('Minmetals, MCC','Yes');
INSERT INTO Investment_Company VALUES('Minmetals, Suzhou Guoxin, China International Trust and Investment (CITIC)','Yes');
INSERT INTO Investment_Company VALUES('Minmetals, Xinxing Iron','Yes');
INSERT INTO Investment_Company VALUES('Moon Lake Investments','No');
INSERT INTO Investment_Company VALUES('Nanchang Engineering','No');
INSERT INTO Investment_Company VALUES('Nanjing Chervon','No');
INSERT INTO Investment_Company VALUES('Nanjing Iron-led consortium','No');
INSERT INTO Investment_Company VALUES('Nanjinzhao','No');
INSERT INTO Investment_Company VALUES('Nanshan Group','No');
INSERT INTO Investment_Company VALUES('Nantong Fujitsu','No');
INSERT INTO Investment_Company VALUES('Nantong Sanjian','No');
INSERT INTO Investment_Company VALUES('Nantong Sanjian, China Railway Construction','Yes');
INSERT INTO Investment_Company VALUES('NetDragon','No');
INSERT INTO Investment_Company VALUES('NetEase','No');
INSERT INTO Investment_Company VALUES('Nine Dragons','No');
INSERT INTO Investment_Company VALUES('Ninestar, Legend','No');
INSERT INTO Investment_Company VALUES('Ningbo Jifeng','No');
INSERT INTO Investment_Company VALUES('Ningbo Joyson','No');
INSERT INTO Investment_Company VALUES('Ningbo Xusheng','No');
INSERT INTO Investment_Company VALUES('Ningxia Wangfang','No');
INSERT INTO Investment_Company VALUES('Oceanwide Holdings','No');
INSERT INTO Investment_Company VALUES('Oceanwide Holdings, IDG Capital','No');
INSERT INTO Investment_Company VALUES('Orient Securities','No');
INSERT INTO Investment_Company VALUES('Pagoda Investments','No');
INSERT INTO Investment_Company VALUES('Panhua','No');
INSERT INTO Investment_Company VALUES('Perfect World Pictures','No');
INSERT INTO Investment_Company VALUES('Pharmaron Beijing','No');
INSERT INTO Investment_Company VALUES('Phicomm','No');
INSERT INTO Investment_Company VALUES('Ping An','No');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina)','No');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), China Energy Engineering','No');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), China National Machinery Industry (Sinomach)','No');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), China Petroleum and Chemical (Sinopec)','Yes');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), China Railway Construction','Yes');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), China Railway Engineering','Yes');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), HTG','No');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), Jiangsu Zhongli','No');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), Minmetals','Yes');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), Shanghai Construction','No');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), State Grid','Yes');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), Three Gorges','Yes');
INSERT INTO Investment_Company VALUES('Power Construction Corp. (PowerChina), Yingli Green Energy','No');
INSERT INTO Investment_Company VALUES('Primavera Capital','No');
INSERT INTO Investment_Company VALUES('Primavera Capital, Fosun','No');
INSERT INTO Investment_Company VALUES('Primavera Capital, Tencent','No');
INSERT INTO Investment_Company VALUES('Qianhai Zone Authority','No');
INSERT INTO Investment_Company VALUES('Qifeng New Material','No');
INSERT INTO Investment_Company VALUES('Qihoo, Beijing Kunlun','No');
INSERT INTO Investment_Company VALUES('Qingdao Doublestar','No');
INSERT INTO Investment_Company VALUES('Qingdao Hengshun','No');
INSERT INTO Investment_Company VALUES('Qingdao Hengshun Zhongsheng','No');
INSERT INTO Investment_Company VALUES('Qingdao Lu Haifeng','No');
INSERT INTO Investment_Company VALUES('Qingdao Sentury','No');
INSERT INTO Investment_Company VALUES('Qingdao Tianzhong','No');
INSERT INTO Investment_Company VALUES('Qumei Home Furnishing, Huatai Securities','No');
INSERT INTO Investment_Company VALUES('Recon Group','No');
INSERT INTO Investment_Company VALUES('Redco','No');
INSERT INTO Investment_Company VALUES('Reignwood','No');
INSERT INTO Investment_Company VALUES('Renren','No');
INSERT INTO Investment_Company VALUES('Roadbot Tyre','No');
INSERT INTO Investment_Company VALUES('Rongsheng Heavy Industries','No');
INSERT INTO Investment_Company VALUES('Rongsheng Holding, China National Chemical Engineering','Yes');
INSERT INTO Investment_Company VALUES('SAIC Motor (Shanghai Auto)','No');
INSERT INTO Investment_Company VALUES('SAIC Motor (Shanghai Auto), Wuling','No');
INSERT INTO Investment_Company VALUES('Sailun Tire','No');
INSERT INTO Investment_Company VALUES('Sanpower','No');
INSERT INTO Investment_Company VALUES('Sany Heavy Industry','No');
INSERT INTO Investment_Company VALUES('Sany Heavy Industry, China International Trust and Investment (CITIC)','No');
INSERT INTO Investment_Company VALUES('Sanyuan Foods, Fosun','No');
INSERT INTO Investment_Company VALUES('Sequoia Resources','No');
INSERT INTO Investment_Company VALUES('Shaanxi Coal and Chemical','No');
INSERT INTO Investment_Company VALUES('Shaanxi Ligeance','No');
INSERT INTO Investment_Company VALUES('Shaanxi Yanchang Petroleum','Yes');
INSERT INTO Investment_Company VALUES('Shanda Group','No');
INSERT INTO Investment_Company VALUES('Shandong Bright Ruby','No');
INSERT INTO Investment_Company VALUES('Shandong Daiyin','No');
INSERT INTO Investment_Company VALUES('Shandong Dejian','No');
INSERT INTO Investment_Company VALUES('Shandong Electric Power Construction','No');
INSERT INTO Investment_Company VALUES('Shandong Electric Power Construction II','No');
INSERT INTO Investment_Company VALUES('Shandong Electric Power Construction III','No');
INSERT INTO Investment_Company VALUES('Shandong Electric Power Construction III, Dongfang Electric','No');
INSERT INTO Investment_Company VALUES('Shandong Energy','No');
INSERT INTO Investment_Company VALUES('Shandong Gaosu','No');
INSERT INTO Investment_Company VALUES('Shandong Gaosu, China Aircraft Leasing','No');
INSERT INTO Investment_Company VALUES('Shandong Gaosu, China Communications Construction','Yes');
INSERT INTO Investment_Company VALUES('Shandong Gaosu, Power Construction Corp. (PowerChina)','No');
INSERT INTO Investment_Company VALUES('Shandong Gold','No');
INSERT INTO Investment_Company VALUES('Shandong Haohua','No');
INSERT INTO Investment_Company VALUES('Shandong Heavy Industry','No');
INSERT INTO Investment_Company VALUES('Shandong Hengyuan','No');
INSERT INTO Investment_Company VALUES('Shandong Iron','No');
INSERT INTO Investment_Company VALUES('Shandong Kerui','No');
INSERT INTO Investment_Company VALUES('Shandong Landbridge','No');
INSERT INTO Investment_Company VALUES('Shandong Linglong Tire','No');
INSERT INTO Investment_Company VALUES('Shandong Nanshan Aluminum','No');
INSERT INTO Investment_Company VALUES('Shandong Qixing','No');
INSERT INTO Investment_Company VALUES('Shandong Sun Paper','No');
INSERT INTO Investment_Company VALUES('Shandong Tianye','No');
INSERT INTO Investment_Company VALUES('Shandong Weigao','No');
INSERT INTO Investment_Company VALUES('Shandong Weiqiao','No');
INSERT INTO Investment_Company VALUES('Shandong Xinhai, BaoWu Steel (Baosteel)','Yes');
INSERT INTO Investment_Company VALUES('Shandong Yuhuang Chemical','No');
INSERT INTO Investment_Company VALUES('Shangdi Guanqun Investment','No');
INSERT INTO Investment_Company VALUES('Shanghai Construction','No');
INSERT INTO Investment_Company VALUES('Shanghai Giant Network','No');
INSERT INTO Investment_Company VALUES('Shanghai Giant Network-led consortium','No');
INSERT INTO Investment_Company VALUES('Shanghai Gongbao, KaiXinRong','No');
INSERT INTO Investment_Company VALUES('Shanghai Greenland','No');
INSERT INTO Investment_Company VALUES('Shanghai Greenland-led consortium','No');
INSERT INTO Investment_Company VALUES('Shanghai Greenland, China General Technology (Genertec)','Yes');
INSERT INTO Investment_Company VALUES('Shanghai Huafon','No');
INSERT INTO Investment_Company VALUES('Shanghai Industrial Investment, Primavera Capital','No');
INSERT INTO Investment_Company VALUES('Shanghai Inesa','No');
INSERT INTO Investment_Company VALUES('Shanghai International Group, Sanpower','No');
INSERT INTO Investment_Company VALUES('Shanghai International Port Group','No');
INSERT INTO Investment_Company VALUES('Shanghai Lingang','No');
INSERT INTO Investment_Company VALUES('Shanghai MicroPort','No');
INSERT INTO Investment_Company VALUES('Shanghai Municipal Government','No');
INSERT INTO Investment_Company VALUES('Shanghai Municipal Investment','No');
INSERT INTO Investment_Company VALUES('Shanghai Pengxin','No');
INSERT INTO Investment_Company VALUES('Shanghai Putailai','No');
INSERT INTO Investment_Company VALUES('Shanghai Safbon','No');
INSERT INTO Investment_Company VALUES('Shanghai Shenglong','No');
INSERT INTO Investment_Company VALUES('Shanghai Shengong, Shanghai Foreign Economic and Technological Cooperation','No');
INSERT INTO Investment_Company VALUES('Shanghai Shentong','No');
INSERT INTO Investment_Company VALUES('Shanghai Stock Exchange, Shenzhen Stock Exchange','No');
INSERT INTO Investment_Company VALUES('Shanghai Supezet','No');
INSERT INTO Investment_Company VALUES('Shanghai Taison','No');
INSERT INTO Investment_Company VALUES('Shanghai Tunnel Engineering','No');
INSERT INTO Investment_Company VALUES('Shanghai United Real Estate','No');
INSERT INTO Investment_Company VALUES('Shanghai Wanfeng','No');
INSERT INTO Investment_Company VALUES('Shanghai Yuyuan Tourist Mart','No');
INSERT INTO Investment_Company VALUES('Shanghai Zendai','No');
INSERT INTO Investment_Company VALUES('Shanghai Zhongfu','No');
INSERT INTO Investment_Company VALUES('Shanghai Zhongji','No');
INSERT INTO Investment_Company VALUES('Shanghai-based consortium','No');
INSERT INTO Investment_Company VALUES('Shanshan Technology','No');
INSERT INTO Investment_Company VALUES('Shanxi Building Material, Asian and African Business Management','No');
INSERT INTO Investment_Company VALUES('Shanxi Coking Coal','No');
INSERT INTO Investment_Company VALUES('Shanxi Construction Investment','No');
INSERT INTO Investment_Company VALUES('Shengli Engineering-led consortium','No');
INSERT INTO Investment_Company VALUES('Shenhua','No');
INSERT INTO Investment_Company VALUES('Shenyang Blue Silver','No');
INSERT INTO Investment_Company VALUES('Shenyang International Cooperation Corp','No');
INSERT INTO Investment_Company VALUES('Shenyang Lan Sa','No');
INSERT INTO Investment_Company VALUES('Shenzhen Energy, China Development Bank','No');
INSERT INTO Investment_Company VALUES('Shenzhen Energy, Power Construction Corp. (PowerChina)','No');
INSERT INTO Investment_Company VALUES('Shenzhen Genzon','No');
INSERT INTO Investment_Company VALUES('Shenzhen Government','No');
INSERT INTO Investment_Company VALUES('Shenzhen Hazens','No');
INSERT INTO Investment_Company VALUES('Shenzhen Hepalink','No');
INSERT INTO Investment_Company VALUES('Shenzhen Huafu','No');
INSERT INTO Investment_Company VALUES('Shenzhen Invengo','No');
INSERT INTO Investment_Company VALUES('Shenzhen Metro, China Railway Construction','Yes');
INSERT INTO Investment_Company VALUES('Shenzhen Xingyuan','No');
INSERT INTO Investment_Company VALUES('Shenzhen Yuhu','No');
INSERT INTO Investment_Company VALUES('Shenzhen Zhongjin Lingnan','No');
INSERT INTO Investment_Company VALUES('Shimao','No');
INSERT INTO Investment_Company VALUES('Shougang Group','No');
INSERT INTO Investment_Company VALUES('Shuanghui','No');
INSERT INTO Investment_Company VALUES('Shuifa Group','No');
INSERT INTO Investment_Company VALUES('Shunde Rixin, Minmetals','Yes');
INSERT INTO Investment_Company VALUES('Sichuan Bohong','No');
INSERT INTO Investment_Company VALUES('Sichuan Changhong','No');
INSERT INTO Investment_Company VALUES('Sichuan consortium','No');
INSERT INTO Investment_Company VALUES('Sichuan Department of Agriculture','No');
INSERT INTO Investment_Company VALUES('Sichuan Hanlong','No');
INSERT INTO Investment_Company VALUES('Sichuan Railway Industry','No');
INSERT INTO Investment_Company VALUES('Sichuan Railway Investment','No');
INSERT INTO Investment_Company VALUES('Sichuan Xinglida','No');
INSERT INTO Investment_Company VALUES('Sichuan Yahua Industrial','No');
INSERT INTO Investment_Company VALUES('Sino Biopharm','No');
INSERT INTO Investment_Company VALUES('Sino Great Wall','No');
INSERT INTO Investment_Company VALUES('Sino-Europe Sports','No');
INSERT INTO Investment_Company VALUES('Sinocare','No');
INSERT INTO Investment_Company VALUES('Sinochem','Yes');
INSERT INTO Investment_Company VALUES('Sinoenergy','No');
INSERT INTO Investment_Company VALUES('Sinohydro, China Communications Construction','Yes');
INSERT INTO Investment_Company VALUES('Sinohydro, Three Gorges','Yes');
INSERT INTO Investment_Company VALUES('Sinolight','No');
INSERT INTO Investment_Company VALUES('Sinoma','No');
INSERT INTO Investment_Company VALUES('Sinosteel','No');
INSERT INTO Investment_Company VALUES('Sinosteel, Power Construction Corp. (PowerChina)','No');
INSERT INTO Investment_Company VALUES('Sinovac','No');
INSERT INTO Investment_Company VALUES('Sirio Pharma','No');
INSERT INTO Investment_Company VALUES('Skyworth','No');
INSERT INTO Investment_Company VALUES('Soho China','No');
INSERT INTO Investment_Company VALUES('Solargiga','No');
INSERT INTO Investment_Company VALUES('Songcheng Performance','No');
INSERT INTO Investment_Company VALUES('Southern Power Grid','Yes');
INSERT INTO Investment_Company VALUES('Southern Power Grid, State Power Investment Corporation','Yes');
INSERT INTO Investment_Company VALUES('Spearhead','No');
INSERT INTO Investment_Company VALUES('StarTimes','No');
INSERT INTO Investment_Company VALUES('State Administration of Foreign Exchange (SAFE)','No');
INSERT INTO Investment_Company VALUES('State Administration of Foreign Exchange (SAFE), China Merchants','Yes');
INSERT INTO Investment_Company VALUES('State Administration of Foreign Exchange (SAFE), China Reform Holdings','No');
INSERT INTO Investment_Company VALUES('State Construction Engineering','No');
INSERT INTO Investment_Company VALUES('State Construction Engineering, China Communications Construction','Yes');
INSERT INTO Investment_Company VALUES('State Construction Engineering, Power Construction Corp. (PowerChina), China Communications Construction','Yes');
INSERT INTO Investment_Company VALUES('State Construction Engineering, Wengfu Group','No');
INSERT INTO Investment_Company VALUES('State Development and Investment Corp.','Yes');
INSERT INTO Investment_Company VALUES('State Development and Investment Corp., Anhui Conch','Yes');
INSERT INTO Investment_Company VALUES('State Development and Investment Corp., Gansu International Cooperation Corp','Yes');
INSERT INTO Investment_Company VALUES('State Grid','Yes');
INSERT INTO Investment_Company VALUES('State Grid, Power Construction Corp. (PowerChina)','Yes');
INSERT INTO Investment_Company VALUES('State Power Investment Corporation, Aviation Industry Corp. (AVIC)','Yes');
INSERT INTO Investment_Company VALUES('Sun Share Investments','No');
INSERT INTO Investment_Company VALUES('Suning','No');
INSERT INTO Investment_Company VALUES('Sunlon, China International Trust and Investment (CITIC)','No');
INSERT INTO Investment_Company VALUES('Sunny Yi Feng','No');
INSERT INTO Investment_Company VALUES('Sunshine Insurance','No');
INSERT INTO Investment_Company VALUES('Suzhou Dongshan','No');
INSERT INTO Investment_Company VALUES('Svolt','No');
INSERT INTO Investment_Company VALUES('Synutra','No');
INSERT INTO Investment_Company VALUES('Taikang Life','No');
INSERT INTO Investment_Company VALUES('Taiping Life','No');
INSERT INTO Investment_Company VALUES('Taiyuan Heavy','No');
INSERT INTO Investment_Company VALUES('Taiyuan Iron, China Development Bank, Shanxi Coking Coal, and Tianli Enterprises','No');
INSERT INTO Investment_Company VALUES('Taiyuan Iron, China International Trust and Investment (CITIC), BaoWu Steel (Baosteel)','Yes');
INSERT INTO Investment_Company VALUES('Tangshan Jidong Cement, China Development Bank','No');
INSERT INTO Investment_Company VALUES('TCL','No');
INSERT INTO Investment_Company VALUES('Tebian Electric Apparatus (TBEA)-led consortium','No');
INSERT INTO Investment_Company VALUES('Tebian Electric Apparatus (TBEA), Power Construction Corp. (PowerChina)','No');
INSERT INTO Investment_Company VALUES('Tempo Group, Beijing Municipal Government','No');
INSERT INTO Investment_Company VALUES('Tempus','No');
INSERT INTO Investment_Company VALUES('Tencent','No');
INSERT INTO Investment_Company VALUES('Tencent-led consortium','No');
INSERT INTO Investment_Company VALUES('Tencent, Hillhouse Capital, Meituan Dianping','No');
INSERT INTO Investment_Company VALUES('Tencent, JD.Com','No');
INSERT INTO Investment_Company VALUES('Tencent, Legend','No');
INSERT INTO Investment_Company VALUES('Tencent, Renren','No');
INSERT INTO Investment_Company VALUES('Texhong Textile','No');
INSERT INTO Investment_Company VALUES('Three Gorges','Yes');
INSERT INTO Investment_Company VALUES('Three Gorges-led consortium','Yes');
INSERT INTO Investment_Company VALUES('Three Gorges, China Development Bank','Yes');
INSERT INTO Investment_Company VALUES('Three Gorges, Sinohydro','Yes');
INSERT INTO Investment_Company VALUES('Tianjin Development','No');
INSERT INTO Investment_Company VALUES('Tianjin Pipe','No');
INSERT INTO Investment_Company VALUES('Tianjin Zhonghuan Semi','No');
INSERT INTO Investment_Company VALUES('Tianshui Huatian','No');
INSERT INTO Investment_Company VALUES('Tianyu Group','No');
INSERT INTO Investment_Company VALUES('Tibet Summit','No');
INSERT INTO Investment_Company VALUES('Tibet Yiwei','No');
INSERT INTO Investment_Company VALUES('Tidfore Heavy','No');
INSERT INTO Investment_Company VALUES('Tidfore Heavy Equipment','No');
INSERT INTO Investment_Company VALUES('Trip.com (formerly Ctrip.com)','No');
INSERT INTO Investment_Company VALUES('Truking Group','No');
INSERT INTO Investment_Company VALUES('Tsinghua Holdings','No');
INSERT INTO Investment_Company VALUES('Tsinghua Holdings, China International Trust and Investment (CITIC)','No');
INSERT INTO Investment_Company VALUES('Tsingshan','No');
INSERT INTO Investment_Company VALUES('Tsingshan, Shanghai Huafon','No');
INSERT INTO Investment_Company VALUES('Tsingtao Beer','No');
INSERT INTO Investment_Company VALUES('Union Development','No');
INSERT INTO Investment_Company VALUES('United Energy','No');
INSERT INTO Investment_Company VALUES('United Energy, Ningbo Orient','No');
INSERT INTO Investment_Company VALUES('Universal Energy','No');
INSERT INTO Investment_Company VALUES('Universal Scientific Industrial','No');
INSERT INTO Investment_Company VALUES('Uphill Investment','No');
INSERT INTO Investment_Company VALUES('Venus Medtech','No');
INSERT INTO Investment_Company VALUES('Vision Investment','No');
INSERT INTO Investment_Company VALUES('Visual China','No');
INSERT INTO Investment_Company VALUES('Viva China','No');
INSERT INTO Investment_Company VALUES('Wallaby Medical','No');
INSERT INTO Investment_Company VALUES('Wanbao Grain','No');
INSERT INTO Investment_Company VALUES('Wanfeng Auto','No');
INSERT INTO Investment_Company VALUES('Wangsu S&T','No');
INSERT INTO Investment_Company VALUES('Wanhua Industrial','No');
INSERT INTO Investment_Company VALUES('Wanxiang','No');
INSERT INTO Investment_Company VALUES('Weihai','No');
INSERT INTO Investment_Company VALUES('West China Cement','No');
INSERT INTO Investment_Company VALUES('WH Group (formerly Shuanghui)','No');
INSERT INTO Investment_Company VALUES('Wingtech','No');
INSERT INTO Investment_Company VALUES('Wise Road Capital','No');
INSERT INTO Investment_Company VALUES('Wison Engineering','No');
INSERT INTO Investment_Company VALUES('Wolong','No');
INSERT INTO Investment_Company VALUES('Wuhan Iron and Steel','No');
INSERT INTO Investment_Company VALUES('Wuhan Iron and Steel, China Development Bank','No');
INSERT INTO Investment_Company VALUES('Wuhan Kaidi Electric','No');
INSERT INTO Investment_Company VALUES('Wuhan Zhengtang','No');
INSERT INTO Investment_Company VALUES('WuXi AppTec','No');
INSERT INTO Investment_Company VALUES('Wuxi No. 1 Cotton Mill','No');
INSERT INTO Investment_Company VALUES('WuXi Pharma','No');
INSERT INTO Investment_Company VALUES('Wuxi Suntech','No');
INSERT INTO Investment_Company VALUES('Xiamen University','No');
INSERT INTO Investment_Company VALUES('Xiamen Xiangyu','No');
INSERT INTO Investment_Company VALUES('Xian Longi','No');
INSERT INTO Investment_Company VALUES('Xiaomi','No');
INSERT INTO Investment_Company VALUES('Xin Zhong Yuan','No');
INSERT INTO Investment_Company VALUES('Xinghai Group','No');
INSERT INTO Investment_Company VALUES('Xinjiang Beiken Energy Engineering','No');
INSERT INTO Investment_Company VALUES('Xinjiang Communications Construction','Yes');
INSERT INTO Investment_Company VALUES('Xinjiang Goldwind, China Energy Conservation and Environmental Protection','Yes');
INSERT INTO Investment_Company VALUES('Xinjiang Goldwind, Power Construction Corp. (PowerChina)','No');
INSERT INTO Investment_Company VALUES('Xinjiang Guanghui','No');
INSERT INTO Investment_Company VALUES('Xinjiang Hualing','No');
INSERT INTO Investment_Company VALUES('Xinjiang Hualing, Shanghai Boda','No');
INSERT INTO Investment_Company VALUES('Xinwei','No');
INSERT INTO Investment_Company VALUES('Xinyi Glass','No');
INSERT INTO Investment_Company VALUES('Xiwang Group, Primavera Capital','No');
INSERT INTO Investment_Company VALUES('Xtep International','No');
INSERT INTO Investment_Company VALUES('Xuzhou Construction Machinery','No');
INSERT INTO Investment_Company VALUES('Yangzijiang Shipbuilding','No');
INSERT INTO Investment_Company VALUES('Yanjian','No');
INSERT INTO Investment_Company VALUES('Yankuang Group','No');
INSERT INTO Investment_Company VALUES('Yanlord','No');
INSERT INTO Investment_Company VALUES('Yanlord-led consortium','No');
INSERT INTO Investment_Company VALUES('Yantai Xinchao','No');
INSERT INTO Investment_Company VALUES('Yatsen','No');
INSERT INTO Investment_Company VALUES('Yida','No');
INSERT INTO Investment_Company VALUES('Yifan Pharmaceuticals','No');
INSERT INTO Investment_Company VALUES('Yinniu Microelectronics-led consortium','No');
INSERT INTO Investment_Company VALUES('Yonghui Superstores Co.','No');
INSERT INTO Investment_Company VALUES('Youngor','No');
INSERT INTO Investment_Company VALUES('Yu Kuo','No');
INSERT INTO Investment_Company VALUES('Yuanda','No');
INSERT INTO Investment_Company VALUES('YuanMing Capital-led consortium','No');
INSERT INTO Investment_Company VALUES('Yuetai','No');
INSERT INTO Investment_Company VALUES('Yunnan Construction and Investment','No');
INSERT INTO Investment_Company VALUES('Yunnan Construction Engineering','No');
INSERT INTO Investment_Company VALUES('Yunnan Copper-led consortium','No');
INSERT INTO Investment_Company VALUES('Yunnan Dongyan','No');
INSERT INTO Investment_Company VALUES('Yunnan Energy Investment','No');
INSERT INTO Investment_Company VALUES('Yunnan Energy New Material','No');
INSERT INTO Investment_Company VALUES('Yunnan Metallurgical','Yes');
INSERT INTO Investment_Company VALUES('Yunyi Guokai Shanghai','No');
INSERT INTO Investment_Company VALUES('YY','No');
INSERT INTO Investment_Company VALUES('Zanyu Technology','No');
INSERT INTO Investment_Company VALUES('Zarsion','No');
INSERT INTO Investment_Company VALUES('Zhejiang Chint','No');
INSERT INTO Investment_Company VALUES('Zhejiang Geely','No');
INSERT INTO Investment_Company VALUES('Zhejiang Hengyi','No');
INSERT INTO Investment_Company VALUES('Zhejiang Huayou Cobalt','No');
INSERT INTO Investment_Company VALUES('Zhejiang Huayou Cobalt, China Molybdenum, Tsingshan','No');
INSERT INTO Investment_Company VALUES('Zhejiang Jinke','No');
INSERT INTO Investment_Company VALUES('Zhejiang Lygend','No');
INSERT INTO Investment_Company VALUES('Zhejiang Rongsheng, Shanghai Zhongrong, Legend','No');
INSERT INTO Investment_Company VALUES('Zhejiang Semir','No');
INSERT INTO Investment_Company VALUES('Zhejiang Weiming','No');
INSERT INTO Investment_Company VALUES('Zhejiang Xinao','No');
INSERT INTO Investment_Company VALUES('Zhejiang Xinshengda','No');
INSERT INTO Investment_Company VALUES('Zhejiang Yongjin','No');
INSERT INTO Investment_Company VALUES('Zhengzhou Coal, Renaissance Capital','No');
INSERT INTO Investment_Company VALUES('Zhongding International Construction','No');
INSERT INTO Investment_Company VALUES('Zhonghong Zhuoye','No');
INSERT INTO Investment_Company VALUES('Zhongli','No');
INSERT INTO Investment_Company VALUES('Zhongman Petroleum','Yes');
INSERT INTO Investment_Company VALUES('Zhongmei Engineering','No');
INSERT INTO Investment_Company VALUES('Zhongrong Xinda','No');
INSERT INTO Investment_Company VALUES('Zhongrun Resources','No');
INSERT INTO Investment_Company VALUES('Zhongwang','No');
INSERT INTO Investment_Company VALUES('Zhouda Real Estate','No');
INSERT INTO Investment_Company VALUES('Zhuhai Port Holdings, State Construction Engineering','No');
INSERT INTO Investment_Company VALUES('Zhuhai Zhenrong','No');
INSERT INTO Investment_Company VALUES('Zhuzhou Kibing','No');
INSERT INTO Investment_Company VALUES('Zijin Mining','No');
INSERT INTO Investment_Company VALUES('Zijin Mining, China Nonferrous, Xiamen C&D','Yes');
INSERT INTO Investment_Company VALUES('ZOJE Resources','No');
INSERT INTO Investment_Company VALUES('Zongshen Industrial','No');
INSERT INTO Investment_Company VALUES('Zoomlion','No');
INSERT INTO Investment_Company VALUES('ZTE (Zhongxing Telecommunications Equipment)','No');
INSERT INTO Investment_Company VALUES('ZTE (Zhongxing Telecommunications Equipment), China Telecom','No');
INSERT INTO Investment_Company VALUES('ZTE (Zhongxing Telecommunications Equipment), Huawei Technologies, China Communications Construction','Yes');
COMMIT;
